GET http://localhost:5000/Users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsIm5hbWUiOiJzZWxlbmEiLCJlbWFpbCI6InRoMkBnbWFpbC5jb20iLCJpYXQiOjE2NDM0NDM2MjIsImV4cCI6MTY0MzQ0MzY0Mn0.X-9i_KnVrDTeqGrpuC1P-_q1i7eE0kMv7oGXHO6vCeo
###
POST http://localhost:5000/Users
Content-Type: application/json

{
    "name": "duadua",
    "email": "dua2@gmail.com",
    "password": "22",
    "confPassword": "22"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "th2@gmail.com",
    "password": "212"
}

###
GET http://localhost:5000/token

###
DELETE  http://localhost:5000/logout